const mongoose = require("mongoose");

const answerSchema = new mongoose.Schema(
  {
    // Question that this answer belongs to.
    question: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Question",
      required: true,
      index: true,
    },
    // User who wrote the answer. Null is allowed for system-generated drafts.
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },
    // Main answer content shown on the question detail page.
    body: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
      maxlength: 5000,
    },
    // True when the answer was generated by AI as a provisional draft.
    aiGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
    // True when this answer is accepted as the best/resolving answer.
    isAccepted: {
      type: Boolean,
      default: false,
      index: true,
    },
    // True when this answer is an admin/system verified official response.
    isOfficial: {
      type: Boolean,
      default: false,
      index: true,
    },
    // Cached upvote count for ranking and display.
    upvoteCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    // Cached downvote count for ranking and display.
    downvoteCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    // Users who have upvoted this answer. Used to prevent duplicate votes.
    upvotedBy: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: "User",
      default: [],
      select: false,
    },
    // Users who have downvoted this answer. Used to prevent duplicate votes.
    downvotedBy: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: "User",
      default: [],
      select: false,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Computed score used by API responses and sorting logic.
answerSchema.virtual("netVoteScore").get(function () {
  return this.upvoteCount - this.downvoteCount;
});

answerSchema.virtual("comments", {
  ref:          "Comment",
  localField:   "_id",
  foreignField: "parentId",
  match:        { parentType: "Answer" },
});

module.exports = mongoose.model("Answer", answerSchema);
