/**
 * registerOfflineServiceWorker.test — unit tests for enableOfflineMode /
 * disableOfflineMode / isOfflineModeRegistered in registerOfflineServiceWorker.ts.
 *
 * `virtual:pwa-register` is a build-time virtual module generated by
 * vite-plugin-pwa — it doesn't exist as a real file, so it's mocked here
 * the same way any other module dependency is mocked in this repo's
 * existing frontend tests (see AdminAutoAnswerQueue.test.tsx).
 *
 * This is a pure add-on: no source file is modified.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

const registerSWMock = vi.fn();

vi.mock('virtual:pwa-register', () => ({
  registerSW: (opts: any) => registerSWMock(opts),
}));

async function loadModule() {
  vi.resetModules();
  return import('../registerOfflineServiceWorker');
}

describe('registerOfflineServiceWorker', () => {
  let originalServiceWorker: any;
  let originalCaches: any;

  beforeEach(() => {
    registerSWMock.mockReset();
    originalServiceWorker = (navigator as any).serviceWorker;
    originalCaches = (window as any).caches;
  });

  afterEach(() => {
    if (originalServiceWorker === undefined) {
      delete (navigator as any).serviceWorker;
    } else {
      (navigator as any).serviceWorker = originalServiceWorker;
    }
    if (originalCaches === undefined) {
      delete (window as any).caches;
    } else {
      (window as any).caches = originalCaches;
    }
  });

  it('isOfflineModeRegistered is false before enableOfflineMode is called', async () => {
    const mod = await loadModule();
    expect(mod.isOfflineModeRegistered()).toBe(false);
  });

  it('warns and no-ops when serviceWorker is unsupported', async () => {
    delete (navigator as any).serviceWorker;
    const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

    const mod = await loadModule();
    await mod.enableOfflineMode();

    expect(registerSWMock).not.toHaveBeenCalled();
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining('Service workers are not supported'),
    );
    warnSpy.mockRestore();
  });

  it('registers the service worker and flips isOfflineModeRegistered to true', async () => {
    (navigator as any).serviceWorker = { getRegistrations: vi.fn().mockResolvedValue([]) };
    const fakeRegistration = { unregister: vi.fn().mockResolvedValue(true) };
    registerSWMock.mockImplementation((opts: any) => {
      opts.onRegisteredSW?.('/sw.js', fakeRegistration);
    });

    const mod = await loadModule();
    await mod.enableOfflineMode();

    expect(registerSWMock).toHaveBeenCalledWith(
      expect.objectContaining({ immediate: true }),
    );
    expect(mod.isOfflineModeRegistered()).toBe(true);
  });

  it('is safe to call enableOfflineMode twice — second call is a no-op', async () => {
    (navigator as any).serviceWorker = { getRegistrations: vi.fn().mockResolvedValue([]) };
    const fakeRegistration = { unregister: vi.fn().mockResolvedValue(true) };
    registerSWMock.mockImplementation((opts: any) => {
      opts.onRegisteredSW?.('/sw.js', fakeRegistration);
    });

    const mod = await loadModule();
    await mod.enableOfflineMode();
    await mod.enableOfflineMode();

    expect(registerSWMock).toHaveBeenCalledTimes(1);
  });

  it('logs an error via onRegisterError without throwing', async () => {
    (navigator as any).serviceWorker = { getRegistrations: vi.fn().mockResolvedValue([]) };
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    registerSWMock.mockImplementation((opts: any) => {
      opts.onRegisterError?.(new Error('boom'));
    });

    const mod = await loadModule();
    await expect(mod.enableOfflineMode()).resolves.not.toThrow();

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining('Service worker registration failed'),
      expect.any(Error),
    );
    errorSpy.mockRestore();
  });

  it('disableOfflineMode unregisters the active registration and clears matching caches', async () => {
    const unregister = vi.fn().mockResolvedValue(true);
    (navigator as any).serviceWorker = { getRegistrations: vi.fn().mockResolvedValue([]) };
    registerSWMock.mockImplementation((opts: any) => {
      opts.onRegisteredSW?.('/sw.js', { unregister });
    });

    const deleteCache = vi.fn().mockResolvedValue(true);
    (window as any).caches = {
      keys: vi.fn().mockResolvedValue(['faq-api-cache-v1', 'workbox-precache-v2', 'unrelated-cache']),
      delete: deleteCache,
    };

    const mod = await loadModule();
    await mod.enableOfflineMode();
    expect(mod.isOfflineModeRegistered()).toBe(true);

    await mod.disableOfflineMode();

    expect(unregister).toHaveBeenCalled();
    expect(deleteCache).toHaveBeenCalledWith('faq-api-cache-v1');
    expect(deleteCache).toHaveBeenCalledWith('workbox-precache-v2');
    expect(deleteCache).not.toHaveBeenCalledWith('unrelated-cache');
    expect(mod.isOfflineModeRegistered()).toBe(false);
  });

  it('disableOfflineMode is safe to call when nothing was ever registered', async () => {
    (navigator as any).serviceWorker = { getRegistrations: vi.fn().mockResolvedValue([]) };
    const mod = await loadModule();

    await expect(mod.disableOfflineMode()).resolves.not.toThrow();
  });
});
