import mongoose, { Document, Schema as MongooseSchema, Types } from 'mongoose';

// ─── Enums ───────────────────────────────────────────────────────────────────

export type SupportIssueType = 'internet' | 'camera' | 'microphone' | 'device' | 'power' | 'other';
// ── 5-state lifecycle (additive, v1.65 — Golden Ticket extension) ──
// Pre-v1.65 states ('Pending' | 'In Review' | 'Resolved' | 'Rejected')
// remain valid; existing tickets in those states are unchanged. The
// two new states are only written by admin transitions / the
// convert-to-golden flow. New tickets still default to 'Pending' so
// the existing admin inbox filter (status='Pending') keeps matching.
export type SupportStatus = 'Pending' | 'In Review' | 'Resolved' | 'Rejected' | 'open' | 'closed';
// v1.68 — schema audit note: this enum has TitleCase +
// lowercase mixed (the v1.65 Golden extension added the
// lowercase values; the v1.5 admin inbox had the
// TitleCase values). The audit recommends normalizing to
// lowercase only. KEPT AS-IS in v1.68 to avoid breaking
// ~20 controller / script call sites that compare against
// the TitleCase values. A follow-up commit can normalize
// the DB values via LEGACY_STATUS_MAP and remove the
// TitleCase variants. Tracked in issues.md schema-audit M1.

// v1.68 — compatibility map for the future normalization.
// New writes should use the lowercase form. Old DB rows
// carry TitleCase values; the controller can normalize
// on read using this map.
export const LEGACY_STATUS_MAP: Record<string, SupportStatus> = {
  Pending: 'Pending', // already canonical
  'In Review': 'In Review', // already canonical
  Resolved: 'Resolved', // already canonical
  Rejected: 'Rejected', // already canonical
  open: 'open',
  closed: 'closed',
};
export type SupportSenderRole = 'admin' | 'student';

// Default issue-type display labels + 4-step checklists. These are
// seeded into the AttendanceGuidance collection on first read; admins
// can override any of them via PUT /api/support/guidance/:issueType.
export const ISSUE_CONFIGS: Record<
  SupportIssueType,
  {
    label: string;
    shortLabel: string;
    steps: string[];
  }
> = {
  internet: {
    label: 'Internet Problem',
    shortLabel: 'Internet',
    steps: [
      'Restart your router or hotspot once.',
      'Switch to a backup network if one is available.',
      'Disable VPN or proxy tools that may interfere with the class link.',
      'Note the time the connection dropped so the team can review it.',
    ],
  },
  camera: {
    label: 'Camera Issue',
    shortLabel: 'Camera',
    steps: [
      'Check browser camera permission in the address bar.',
      'Close and reopen the class tab, then test your camera again.',
      'Reconnect the camera or switch to another device if you have one.',
      'Write down the exact browser or device error if the camera still fails.',
    ],
  },
  microphone: {
    label: 'Microphone Issue',
    shortLabel: 'Microphone',
    steps: [
      'Check microphone permission in the browser.',
      'Unplug and reconnect the mic or headset if you are using one.',
      'Test microphone input in another app to confirm the device works.',
      'Write down the browser or device message you saw.',
    ],
  },
  device: {
    label: 'Device Failure',
    shortLabel: 'Device',
    steps: [
      'Restart the device once and try reconnecting to the class.',
      'Plug in power or move to another device if one is available.',
      'If the device is overheating or crashing, stop using it for a moment.',
      'Write down any boot, crash, or hardware message you see.',
    ],
  },
  power: {
    label: 'Power Outage',
    shortLabel: 'Power',
    steps: [
      'Confirm whether the outage affects only your room or the full area.',
      'Move to a backup power source or a different location if possible.',
      'Use your phone hotspot if mobile data is available.',
      'Mention the outage timing and duration in your request.',
    ],
  },
  other: {
    label: 'Other Reason',
    shortLabel: 'Other',
    steps: [
      'Write a short description of what stopped you from joining.',
      'Note the time the issue started and whether it affected the whole session.',
      'Submit the request so the support team can review it.',
    ],
  },
};

export function getIssueConfig(issueType: string) {
  return (
    (ISSUE_CONFIGS as Record<string, (typeof ISSUE_CONFIGS)[SupportIssueType]>)[issueType] ??
    ISSUE_CONFIGS.other
  );
}

// ─── Subdocuments ────────────────────────────────────────────────────────────

export interface ISupportDocument {
  name: string;
  url: string;
  type: string;
}

export interface ISupportFollowUp {
  _id?: Types.ObjectId; // auto-generated by Mongoose on push
  senderRole: SupportSenderRole;
  senderId: Types.ObjectId;
  senderName: string;
  message: string;
  /** Admin-only flag — marks the message as "please send proof". */
  requestProof: boolean;
  documents: ISupportDocument[];
  createdAt: Date;
}

export interface ISupportInternalNote {
  _id?: Types.ObjectId; // auto-generated by Mongoose on push
  note: string;
  addedBy: Types.ObjectId;
  addedByName: string;
  createdAt: Date;
}

export interface ISupportStatusHistoryEntry {
  _id?: Types.ObjectId; // auto-generated by Mongoose on push
  status: SupportStatus;
  note: string;
  updatedBy: Types.ObjectId;
  updatedByName: string;
  timestamp: Date;
}

// v1.70 — Golden Ticket "re-resolve" trail. When an admin sends an
// additional answer to an already-Resolved Golden ticket, we push a
// new entry here. SP is NEVER charged again (the user paid once at
// raise-time). Each entry captures who answered and when, plus a
// `notificationSent` flag so we can guarantee the user is notified
// about THAT specific answer exactly once via the in-app bell.
export interface IGoldenResolutionEntry {
  _id?: Types.ObjectId;
  text: string;
  adminId: Types.ObjectId;
  adminName: string;
  createdAt: Date;
  // Once the in-app bell fires for THIS entry, flip to true. We
  // never re-notify — the user explicitly asked for "no further
  // notifications" semantics on every re-resolve except the
  // single in-app bell (no email, no SMS).
  notificationSent: boolean;
}

/**
 * v1.74 — One entry in the Golden Ticket discussion thread. Both
 * sides (admin + ticket owner) can post during the 7-day window
 * that opens with the first admin answer. The first admin answer
 * is flagged `isProminent: true` so the UI can pin it to the top
 * of the thread; every other entry is just a chronological message.
 */
export interface IGoldenDiscussionEntry {
  _id?: Types.ObjectId;
  text: string;
  /** 'admin' for any admin/moderator, 'user' for the ticket owner. */
  senderRole: 'admin' | 'user';
  senderId: Types.ObjectId;
  senderName: string;
  createdAt: Date;
  /** Only set on the first admin answer. Drives the pinned top card. */
  isProminent: boolean;
}

// ─── Document ───────────────────────────────────────────────────────────────

export interface ISupportRequest extends Document {
  // Requester
  userId: Types.ObjectId;
  userName: string;
  userEmail: string;

  // Issue classification
  issueType: SupportIssueType;
  issueLabel: string;

  // Free-text content
  title: string;
  details: string;
  attemptedSteps: string[];

  // Status machine
  status: SupportStatus;
  adminNote: string;
  internalNotes: ISupportInternalNote[];
  resolutionSummary: string;
  sessionAccessUrl: string;
  // v1.66 — terminal-state timestamps + reason (set on
  // admin Resolve / Reject). The status enum already includes
  // 'Resolved' / 'Rejected' but we capture the wall-clock here
  // for the admin audit log and the 48h-expiry display.
  resolvedAt?: Date | null;
  rejectedAt?: Date | null;
  rejectionReason?: string;

  // Follow-up thread
  followUps: ISupportFollowUp[];

  // Immutable status history
  statusHistory: ISupportStatusHistoryEntry[];

  // Provenance — when the user last saw the troubleshooting checklist
  guidanceShownAt: Date | null;

  // ── Schema-driven context fields (additive) ────────────────────────────
  // List of {key, label, value} triples. The label is snapshotted at
  // submit time so the admin view can render the *current* label even
  // if the field's display label was renamed or the field was
  // archived after the ticket was submitted.
  contextFields: { key: string; label: string; value: string | number | boolean | null }[];

  // ── Golden Ticket (additive, v1.65) ──────────────────────────────────
  // `isGolden: false` is the safe default — every existing ticket reads
  // as non-Golden until an admin explicitly converts it via
  // POST /api/admin/support/requests/:id/convert-to-golden.
  isGolden: boolean;
  // SP cost paid (or to be paid) for this Golden ticket. 0 for non-golden.
  spCost: number;
  // Provenance for the conversion: when did an admin promote this, and who.
  goldenConvertedAt: Date | null;
  goldenConvertedBy: Types.ObjectId | null;
  goldenConvertedByName: string;
  // If the Golden ticket was rejected, surface the reason in the user view
  // and stamp a cooldown so the same user can't immediately retry.
  goldenRejectionReason: string;
  goldenRejectionEndsAt: Date | null;

  /**
   * v1.70 — Golden Ticket "re-resolve" log. Each entry is an
   * additional answer an admin sent AFTER the initial resolution.
   * The user paid SP exactly once at raise-time; these entries are
   * free follow-ups and cost nothing. Rendered as admin bubbles in
   * the admin queue and surfaced (read-only) on the user thread so
   * the user can see the conversation continuing without being
   * re-notified beyond a single in-app bell per entry.
   */
  goldenResolutions: IGoldenResolutionEntry[];

  /**
   * v1.74 — Golden Ticket discussion thread. After the first admin
   * answer is posted, both sides can reply in chronological order
   * for `GOLDEN_DISCUSSION_WINDOW_MS` (7 days). The first admin
   * answer is flagged `isProminent: true` so the UI can pin it to
   * the top of the thread. Replaces the prior "answers only"
   * behaviour with a true two-way conversation.
   *
   * `firstAdminAnswerAt` is stamped when the FIRST admin entry is
   * pushed; `discussionClosesAt` is computed from it. Both are
   * null until the first answer lands.
   */
  goldenTicketDiscussion: IGoldenDiscussionEntry[];
  firstAdminAnswerAt: Date | null;
  discussionClosesAt: Date | null;

  /**
   * v1.69 — Program this support ticket was opened within. Most
   * support is program-agnostic (a flaky laptop doesn't care which
   * cohort the user is in) but admins want the ability to slice
   * "open tickets for Yaksha 2026-27" separately from "all open".
   */
  batchId?: Types.ObjectId | null;

  createdAt: Date;
  updatedAt: Date;
}

const documentSubSchema = new MongooseSchema<ISupportDocument>(
  {
    name: { type: String, default: '' },
    url: { type: String, default: '' },
    type: { type: String, default: '' },
  },
  { _id: false }
);

const followUpSubSchema = new MongooseSchema<ISupportFollowUp>(
  {
    senderRole: { type: String, enum: ['admin', 'student'] as SupportSenderRole[], required: true },
    senderId: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true },
    senderName: { type: String, required: true, trim: true, maxlength: 100 },
    message: { type: String, required: true, trim: true, maxlength: 2000 },
    requestProof: { type: Boolean, default: false },
    documents: { type: [documentSubSchema], default: [] },
    createdAt: { type: Date, default: Date.now },
  },
  { _id: true }
);

const internalNoteSubSchema = new MongooseSchema<ISupportInternalNote>(
  {
    note: { type: String, required: true, trim: true, maxlength: 2000 },
    addedBy: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true },
    addedByName: { type: String, required: true, maxlength: 100 },
    createdAt: { type: Date, default: Date.now },
  },
  { _id: true }
);

const statusHistorySubSchema = new MongooseSchema<ISupportStatusHistoryEntry>(
  {
    // v1.65: enum extended with 'open' and 'closed' (Golden Ticket lifecycle).
    // Existing 'Pending' | 'In Review' | 'Resolved' | 'Rejected' continue
    // to write to history — no migration on existing entries needed.
    status: {
      type: String,
      enum: ['Pending', 'In Review', 'Resolved', 'Rejected', 'open', 'closed'] as SupportStatus[],
      required: true,
    },
    note: { type: String, default: '', maxlength: 2000 },
    updatedBy: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true },
    updatedByName: { type: String, required: true, maxlength: 100 },
    timestamp: { type: Date, default: Date.now },
  },
  { _id: true }
);

const supportRequestSchema = new MongooseSchema<ISupportRequest>(
  {
    userId: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true, index: true },
    // v1.69 — see interface.
    batchId: {
      type: MongooseSchema.Types.ObjectId,
      ref: 'Batch',
      default: null,
      index: true,
    },
    userName: { type: String, required: true, trim: true, maxlength: 100 },
    userEmail: { type: String, required: true, trim: true, lowercase: true, maxlength: 200 },

    issueType: {
      type: String,
      enum: ['internet', 'camera', 'microphone', 'device', 'power', 'other'] as SupportIssueType[],
      required: true,
      index: true,
    },
    issueLabel: { type: String, required: true, maxlength: 80 },

    title: { type: String, required: true, trim: true, maxlength: 180 },
    details: { type: String, required: true, trim: true, maxlength: 4000 },
    attemptedSteps: { type: [String], default: [] },

    status: {
      // v1.65: enum extended with 'open' and 'closed' (Golden Ticket
      // lifecycle). Existing tickets and the existing 'Pending' default
      // are unchanged. New admin transitions to 'open' / 'closed' only
      // happen via the Golden Ticket / status-update endpoints.
      type: String,
      enum: ['Pending', 'In Review', 'Resolved', 'Rejected', 'open', 'closed'] as SupportStatus[],
      default: 'Pending',
      index: true,
    },
    adminNote: { type: String, default: '', maxlength: 2000 },
    internalNotes: { type: [internalNoteSubSchema], default: [] },
    resolutionSummary: { type: String, default: '', maxlength: 2000 },
    sessionAccessUrl: { type: String, default: '', maxlength: 500 },
    // v1.66 — terminal-state timestamps + reason (see interface).
    resolvedAt: { type: Date, default: null },
    rejectedAt: { type: Date, default: null },
    rejectionReason: { type: String, default: '', maxlength: 2000 },

    followUps: { type: [followUpSubSchema], default: [] },
    statusHistory: { type: [statusHistorySubSchema], default: [] },

    // Provenance — when the user last saw the troubleshooting checklist
    guidanceShownAt: { type: Date, default: null },

    // ── Schema-driven context fields (additive) ──────────────────────────
    // Stored as a list of {key, label, value} triples so the admin view
    // can render the *current* label even if the field was renamed or
    // archived after this ticket was submitted. Key is the immutable
    // schema identifier; value is the canonical type-coerced input.
    contextFields: {
      type: [
        {
          _id: false,
          key: { type: String, required: true, trim: true, maxlength: 60 },
          label: { type: String, required: true, trim: true, maxlength: 120 },
          value: { type: MongooseSchema.Types.Mixed, default: null },
        },
      ],
      default: [],
    },

    // ── Golden Ticket fields (additive, v1.65) ────────────────────────────
    // All default to safe, non-Golden values so existing documents in the
    // `yaksha_faq_session_support` collection read as non-Golden without
    // a migration script. Mongoose only applies `default` on insert, so
    // legacy documents missing these fields return `undefined` from
    // `.toObject()` — admin views and the public inbox MUST treat
    // `undefined` and `false` identically. Helpers in supportCore.ts
    // (`isGoldenTicket`, `goldenRejectionActive`) centralise that.
    isGolden: { type: Boolean, default: false },
    spCost: { type: Number, default: 0, min: 0 },
    goldenConvertedAt: { type: Date, default: null },
    goldenConvertedBy: { type: MongooseSchema.Types.ObjectId, ref: 'User', default: null },
    goldenConvertedByName: { type: String, default: '', maxlength: 100 },
    goldenRejectionReason: { type: String, default: '', maxlength: 2000 },
    goldenRejectionEndsAt: { type: Date, default: null },
    // v1.70 — re-resolve trail. Default empty so existing rows read
    // as [] without a migration. Each entry is small (admin text +
    // author + timestamp + 1 boolean) so unbounded growth is bounded
    // only by admin activity on a single ticket — fine for our scale.
    goldenResolutions: {
      type: [
        {
          _id: false,
          text: { type: String, required: true, trim: true, maxlength: 2000 },
          adminId: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true },
          adminName: { type: String, required: true, trim: true, maxlength: 100 },
          createdAt: { type: Date, default: Date.now },
          notificationSent: { type: Boolean, default: false },
        },
      ],
      default: [],
    },
    // v1.74 — Golden Ticket discussion thread. The first admin
    // answer stamps `firstAdminAnswerAt` + `discussionClosesAt`
    // (now + 7d) and is pushed here with `isProminent: true`.
    // Both sides can reply while the window is open; replies
    // arrive in chronological order.
    goldenTicketDiscussion: {
      type: [
        {
          _id: false,
          text: { type: String, required: true, trim: true, maxlength: 2000 },
          senderRole: { type: String, enum: ['admin', 'user'], required: true },
          senderId: { type: MongooseSchema.Types.ObjectId, ref: 'User', required: true },
          senderName: { type: String, required: true, trim: true, maxlength: 100 },
          createdAt: { type: Date, default: Date.now },
          isProminent: { type: Boolean, default: false },
        },
      ],
      default: [],
    },
    firstAdminAnswerAt: { type: Date, default: null },
    discussionClosesAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// Hot query paths

// "My tickets" list — index scan
supportRequestSchema.index({ userId: 1, createdAt: -1 });

// Admin inbox — common filter combo
supportRequestSchema.index({ status: 1, issueType: 1, updatedAt: -1 });

// Admin pending queue (sorted by oldest-first to triage the backlog)
supportRequestSchema.index({ status: 1, createdAt: 1 });

// Status-update race guard (used by controller to prevent two
// simultaneous transitions)
supportRequestSchema.index({ _id: 1, status: 1 });

// v1.65 — Golden Ticket admin inbox: filter Golden vs non-Golden + sort
// golden first (newest). Compound index keeps the admin "Golden" filter
// fast without scanning non-Golden docs.
supportRequestSchema.index({ isGolden: 1, status: 1, createdAt: -1 });
// Cooldown / analytics: count a user's Golden tickets in a date window.
supportRequestSchema.index({ userId: 1, isGolden: 1, createdAt: -1 });

// v1.65.1 — Escalation Queue: spCost desc with createdAt asc
// tiebreaker (oldest first). Filtered by pending statuses.
supportRequestSchema.index({ isGolden: 1, status: 1, spCost: -1, createdAt: 1 });

export default mongoose.model<ISupportRequest>(
  'SupportRequest',
  supportRequestSchema,
  'yaksha_faq_session_support'
);
